### ISSUE TITLE
[ENG][Bug]: Im logged in and I get this error I tried to get stoken but I couldn't do it I don't know how to get it

### ISSUE THREAD

**Issue by muratiste** [DGP-Studio/Snap.Hutao#2019] opened 2024-10-04 14:42 UTC
### Checklist

- [X] I have read [FAQ page](https://hut.ao/advanced/FAQ.html) and [Exception page](https://hut.ao/advanced/exceptions.html) in Snap Hutao document, and my issue is not answered
- [X] I and tried **search feature** in Snap Hutao document site, and no associated article
- [X] My issue is not a [finished issue](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90), and it's not a duplicated issue

### Windows Version

22631.4249

### Snap Hutao Version

1.11.3.0

### Device ID

B170702D7F37D5F577ADB74897DF2467

### Issue Category

MiHoYo Account Panel

### What Happened?

![image](https://github.com/user-attachments/assets/94fae797-bdaf-4bd2-866f-3d0f738c5559)
[SH-Report-93d540a8-f803-44c6-b402-f82ca3b8b30e.zip](https://github.com/user-attachments/files/17260153/SH-Report-93d540a8-f803-44c6-b402-f82ca3b8b30e.zip)
[SH-Report-93d540a8-f803-44c6-b402-f82ca3b8b30e.txt](https://github.com/user-attachments/files/17260154/SH-Report-93d540a8-f803-44c6-b402-f82ca3b8b30e.txt)

### Last Step

- [X] I believe the description above is detail enough to allow developers to reproduce the issue

**Comment by qhy040404** [comment] 2024-10-04 14:44
Duplicate of #1966

**Closed by qhy040404** 2024-10-04 14:44 UTC
Labels: BUG, area-UserPanel, area-Hoyoverse, need-community-help, priority:none

**Comment by SylverVG** [comment] 2024-10-09 08:36
Is there a solution with this problem? I literally cannot use the app without logging in with Hoyolab account. I hope the devs will fix this problem already its been months.
