### ISSUE TITLE
[Bug]: 1.9.9.0被Windows Defender报告木马病毒

### ISSUE THREAD

**Issue by qakcn** [DGP-Studio/Snap.Hutao#1553] opened 2024-04-16 14:33 UTC
### 检查清单

- [X] 我已阅读 Snap Hutao 文档中的[常见问题](https://hut.ao/advanced/FAQ.html)和[常见程序异常](https://hut.ao/advanced/exceptions.html)，我的问题没有在文档中得到解答
- [X] 我知道文档站的导航栏中有**搜索功能**，且已经搜索过相关关键词
- [X] 我的问题不是[已完成](https://github.com/DGP-Studio/Snap.Hutao/issues?q=is%3Aopen+is%3Aissue+label%3A%E5%B7%B2%E5%AE%8C%E6%88%90)的问题也不是一个别人已发布的**重复的**问题

### Windows 版本

22631.3447

### Snap Hutao 版本

1.9.9.0

### 设备 ID

A2025760328284AF45975203C39E0691

### 问题分类

安装和环境

### 发生了什么？

如题。软件内自动更新和从Github Releases下载都是一样的。

![屏幕截图 2024-04-16 222659](https://github.com/DGP-Studio/Snap.Hutao/assets/1809188/b82ee15c-f8ac-45c3-bfcd-8591cc38c2bd)

### 你期望发生的行为？

不被报告病毒，能正常安装。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by BTMuli** [comment] 2024-04-16 17:46
#1499 #1528

**Comment by qakcn** [comment] 2024-04-16 18:34
> #1499 #1528

谢谢。我只是想知道是哪一部份撩动了Windows Defender的敏感神经，居然还能在不同版本触发而且有的触发有的不触发。

**Comment by Masterain98** [comment] 2024-04-16 22:51
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/06d9be28-69e6-4bfa-b7b1-969790731f0a)

Just confirmed the package is marked as malware again, caused by the WD cloud engine, [`Trojan:AndroidOS/ZkarletFlash`](https://go.microsoft.com/fwlink/p/?linkid=849967&Name=Trojan:AndroidOS/ZkarletFlash), interesting report. The review request has been submitted to Microsoft. 

Before the false detection been removed, you have to manually whitelist the file after the download to bypass the deletion by the WD.

**Comment by Masterain98** [comment] 2024-04-16 23:04
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/cac817e9-fd7f-4376-a3b5-9af839025e43)

Cloud detection is removed. However, it's still been detected in client (definition version `1.409.328.0`). In my local test device, it's marked as `Trojan:Script/Wacatac.B!ml`, same to the last time.

**Comment by Masterain98** [comment] 2024-04-17 01:46
![image](https://github.com/DGP-Studio/Snap.Hutao/assets/10614984/1a0eb196-69b7-47b1-a446-6189570747cc)

We have received a response from Microsoft to confirm the false detection has been removed.

**Closed by Masterain98** 2024-04-17 01:46 UTC
Labels: BUG, area-LifeCycle, priority:high
